version: '3.9'

services:
  nginx:
    container_name: learning-php-nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - learning_php
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: learning-php-php
    volumes:
      - ./app:/var/www/project:rw,delegated
    networks:
      - learning_php
    ports:
      - '9000:9000'
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: learning-php-mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./app/database/silexCars:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: db_pass
    networks:
      - learning_php

networks:
  learning_php: